PIP-60 chore: enhance AWS Device Farm workflows with additional run tagging and error handling
- Updated `cd/deploy/mobile/aws/action.yml` to copy configuration files dynamically based on the environment.
- Improved error handling and output logging when scheduling runs using `aws devicefarm schedule-run`.
- Added tagging for scheduled runs with organization, environment, and application-related metadata for better traceability.

diff --git a/cd/deploy/mobile/aws/action.yml b/cd/deploy/mobile/aws/action.yml
--- a/cd/deploy/mobile/aws/action.yml
+++ b/cd/deploy/mobile/aws/action.yml
@@ -106,6 +106,12 @@ inputs:
 runs:
   using: 'composite'
   steps:
+    - name: Copy configurations
+      shell: bash
+      run: |
+        cp -pf ${{ inputs.source_path }}/.cloudopsworks/vars/inputs-${{ inputs.environment }}.yaml ${{ inputs.blueprint_path }}/devicefarm/aws/inputs.yaml
+        cp -pf ${{ inputs.source_path }}/.cloudopsworks/vars/inputs-global.yaml ${{ inputs.blueprint_path }}/devicefarm/aws/
+
     - name: Device Farm Name
       id: device_farm
       working-directory: ${{ inputs.source_path }}
@@ -442,13 +448,20 @@ runs:
         QUALI: ${{ inputs.qualifier != '' && '-' || '' }}${{ inputs.qualifier }}
       run: |
         echo "::group::Schedule Run - Device Pool"
-        aws devicefarm schedule-run \
+        run_arn=$(aws devicefarm schedule-run \
           --region ${{ inputs.aws_region }} \
           --project-arn ${{ steps.device_farm_arn.outputs.result }} \
           --app-arn ${{ steps.upload_pkg.outputs.result }} \
           --device-pool-arn ${{ steps.device_pool_arn.outputs.result }} \
           --name "${REL}-${RELVER}${QUALI}" \
-          --test '${{ steps.test_params_uploaded.outputs.result }}${{ steps.test_params_fuzz.outputs.result }}'
+          --test '${{ steps.test_params_uploaded.outputs.result }}${{ steps.test_params_fuzz.outputs.result }}' \
+          --query 'run.arn' --output text)
+        if [[ -z "$run_arn" ]]; then
+          echo "::error::Failed to schedule run"
+          exit 1
+        else
+          echo "run_arn=$run_arn" >> $GITHUB_OUTPUT 
+        fi
         echo "::endgroup::"
 
     - name: Schedule Run - Specific Devices
@@ -469,11 +482,36 @@ runs:
       run: |
         echo "::group::Schedule Run - Specific Devices"
         # Generate Filter Device - escape with \"
-        aws devicefarm schedule-run \
+        run_arn=$(aws devicefarm schedule-run \
           --region ${{ inputs.aws_region }} \
           --project-arn ${{ steps.device_farm_arn.outputs.result }} \
           --app-arn ${{ steps.upload_pkg.outputs.result }} \
           --device-selection-configuration '${{ steps.device_config_filter.outputs.filter }}' \
           --name "${REL}-${RELVER}${QUALI}" \
-          --test '${{ steps.test_params_uploaded.outputs.result }}${{ steps.test_params_fuzz.outputs.result }}'
+          --test '${{ steps.test_params_uploaded.outputs.result }}${{ steps.test_params_fuzz.outputs.result }}' \
+          --query 'run.arn' --output text)
+        if [[ -z "$run_arn" ]]; then
+          echo "::error::Failed to schedule run"
+          exit 1
+        else
+          echo "run_arn=$run_arn" >> $GITHUB_OUTPUT 
+        fi
         echo "::endgroup::"
+
+    - name: Tag Run
+      shell: bash
+      if: ${{ steps.schedule_run.outputs.run_arn != '' || steps.run_device.outputs.run_arn != '' }}
+      working-directory: ${{ inputs.blueprint_path }}/devicefarms/aws
+      run: |
+        org=$(yq e '.organization_name' inputs-global.yaml)
+        ou=$(yq e '.organization_unit' inputs-global.yaml)
+        app=$(yq e '.environment_name' inputs-global.yaml)
+        owner=$(yq e '.repository_owner' inputs-global.yaml)
+        envname=${{ inputs.environment }}
+        aws devicefarm tag-resource --region ${{ inputs.aws_region }} \
+          --resource-arn ${{ steps.schedule_run.outputs.run_arn != '' && steps.schedule_run.outputs.run_arn || steps.run_device.outputs.run_arn }} \
+          --tags Key=organization,Value="${org}" \
+          Key=organization-unit,Value="${ou}" \
+          Key=application-name,Value="${app}" \
+          Key=application-type,Value="${envname}" \
+          Key=organization-full-name=,Value="${org} ${ou} ${app} ${envname}"
