Support Rust stack alongside Go stack in release process
Updated the release process to handle Rust stacks in addition to Go stacks by modifying conditional checks. Also, commented out the unsupported Elastic Beanstalk Rust stack configuration to reduce unnecessary errors.

diff --git a/cd/deploy/app/pack/stack-config/action.yml b/cd/deploy/app/pack/stack-config/action.yml
--- a/cd/deploy/app/pack/stack-config/action.yml
+++ b/cd/deploy/app/pack/stack-config/action.yml
@@ -92,14 +92,14 @@ runs:
         VAL=$(yq eval '.beanstalk.solution_stack | test("(?i:.*go.*)")' inputs.yaml)
         echo "result=$VAL" >> $GITHUB_OUTPUT
 
-    - name: Get Elastic Beanstalk Rust Stack from inputs-${{ inputs.environment }}.yaml
-      id: rust_stack_eb
-      if: ${{ inputs.cloud_type == 'beanstalk' }}
-      working-directory: ${{ inputs.blueprint_path }}/terraform/${{ inputs.cloud }}/${{ inputs.cloud_type }}
-      shell: bash
-      run: |
-        echo "::error::This is not supported for beanstalk"
-        exit 1
+#    - name: Get Elastic Beanstalk Rust Stack from inputs-${{ inputs.environment }}.yaml
+#      id: rust_stack_eb
+#      if: ${{ inputs.cloud_type == 'beanstalk' }}
+#      working-directory: ${{ inputs.blueprint_path }}/terraform/${{ inputs.cloud }}/${{ inputs.cloud_type }}
+#      shell: bash
+#      run: |
+#        echo "::error::This is not supported for beanstalk"
+#        exit 1
 
     # Get Stacks for Java, Node, and Python if lambda is in cloud_type
     - name: Get Lambda Java Stack from inputs-${{ inputs.environment }}.yaml
